{% set name = "indexed_zstd" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 89c09eaebbfa8a10634934b816cc3baa1a00e616bcc9e81f31546220e853bef6

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython
    - zstd
  run:
    - python
    - zstd

test:
  imports:
    - indexed_zstd
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/martinellimarco/indexed_zstd.git
  summary: Fast random access to zstd files
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ap--
    - martinellimarco
